# Generated by Django 5.2.12 on 2026-04-09 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('adapter_type', models.CharField(choices=[('text', 'Plain Text List'), ('csv', 'CSV / TSV File'), ('misp', 'MISP Feed'), ('taxii', 'TAXII 2.1 Server'), ('json', 'REST API')], default='json', max_length=16)),
                ('url', models.CharField(blank=True, default='', max_length=512)),
                ('api_key_env', models.CharField(blank=True, default='', max_length=64)),
                ('auth_header', models.CharField(blank=True, default='', max_length=64)),
                ('username', models.CharField(blank=True, default='', max_length=256)),
                ('password_env', models.CharField(blank=True, default='', max_length=64)),
                ('collection_id', models.CharField(blank=True, default='', max_length=256)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('last_pulled', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorOfCompromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(db_index=True, max_length=50)),
                ('ioc_value', models.CharField(db_index=True, max_length=500)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'indicators_of_compromise',
                'unique_together': {('ioc_type', 'ioc_value')},
            },
        ),
        migrations.CreateModel(
            name='GeoEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=4)),
                ('continent_code', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('enriched_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='ingestion.indicatorofcompromise')),
            ],
            options={
                'db_table': 'geo_enrichments',
            },
        ),
    ]
