# Generated by Django 6.0.2 on 2026-02-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorOfCompromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ioc_type', models.CharField(db_index=True, max_length=50)),
                ('ioc_value', models.CharField(db_index=True, max_length=500)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indicators_of_compromise',
                'unique_together': {('ioc_type', 'ioc_value')},
            },
        ),
    ]
