# Generated by Django 6.0.1 on 2026-02-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxiiSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('discovery_url', models.URLField()),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('password', models.CharField(blank=True, default='', max_length=200)),
                ('added_after', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StixObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stix_id', models.CharField(db_index=True, max_length=200)),
                ('stix_type', models.CharField(db_index=True, max_length=100)),
                ('spec_version', models.CharField(blank=True, default='', max_length=20)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField()),
                ('source_name', models.CharField(blank=True, default='', max_length=200)),
                ('collection_id', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'unique_together': {('stix_id', 'modified', 'source_name', 'collection_id')},
            },
        ),
    ]
