# Generated by Django 6.0.2 on 2026-02-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxiisource',
            name='checkpoints',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
