# Generated by Django 6.0.2 on 2026-04-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_seed_feeds'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=700, unique=True)),
                ('source_name', models.CharField(max_length=100)),
                ('matched_label', models.CharField(db_index=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'threat_articles',
                'ordering': ['-published_at'],
            },
        ),
    ]
