# Generated by Django 5.2.12 on 2026-03-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_feedsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='sourceurl',
            field=models.CharField(blank=True),
        ),
    ]
