from django.db import migrations

# Generated by Django 6.0.2 on 2026-02-16 02:02
class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_update_ioc_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='name',
        ),
    ]
