# Generated by Django 6.0.2 on 2026-03-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_feedsource_last_pulled'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='adapter_type',
            field=models.CharField(choices=[('json', 'JSON API'), ('csv', 'CSV/TSV File'), ('text', 'Plain Text List'), ('misp', 'MISP Feed'), ('taxii', 'TAXII 2.1 Server')], default='json', max_length=16),
        ),
    ]
