#  Generated by Django 6.0.2 on 2026-02-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_timestamps_to_datetimefield'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorofcompromise',
            unique_together={('ioc_type', 'ioc_value')},
        ),
        migrations.AddField(
            model_name='indicatorofcompromise',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='pattern_type',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='source',
        ),
        migrations.RemoveField(
            model_name='indicatorofcompromise',
            name='source_id',
        ),
    ]
