# Generated by Django 5.2.11 on 2026-03-25 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_feedsource_sourceurl'),
        ('ingestion', '0006_seed_sources'),
    ]

    operations = [
    ]
