# Generated by Django 6.0.2 on 2026-03-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_feedsource_sourceurl'),
        ('ingestion', '0005_add_adapter_type'),
    ]

    operations = [
    ]
