# Generated by Django 6.0.2 on 2026-04-05 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0009_feedsource_explicit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='adapter_type',
            field=models.CharField(choices=[('text', 'Plain Text List'), ('csv', 'CSV / TSV File'), ('misp', 'MISP Feed'), ('taxii', 'TAXII 2.1 Server'), ('json', 'JSON REST API')], default='json', max_length=16),
        ),
        migrations.CreateModel(
            name='GeoEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('country_code', models.CharField(blank=True, default='', max_length=4)),
                ('continent_code', models.CharField(blank=True, default='', max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('enriched_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo', to='ingestion.indicatorofcompromise')),
            ],
            options={
                'db_table': 'geo_enrichments',
            },
        ),
    ]
