# Generated by Django 5.2.12 on 2026-04-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0017_feedsource_taxii_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='auth_header',
            field=models.CharField(blank=True, default='', help_text="HTTP header name for the API key, e.g. 'Auth-Key' or 'X-OTX-API-KEY'. Leave blank if no authentication is needed.", max_length=64),
        ),
        migrations.AlterField(
            model_name='feedsource',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Internal auto-detection cache. Do not edit manually.'),
        ),
    ]
