# Generated by Django 5.2.12 on 2026-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0019_drop_ioc_type_static_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
