# Generated by Django 5.2.10 on 2026-02-13 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.threatfeed')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('domain', 'Domain'), ('url', 'URL'), ('hash', 'File Hash')], max_length=20)),
                ('value', models.CharField(db_index=True, max_length=500)),
                ('confidence', models.IntegerField(default=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_ingested', models.DateTimeField(auto_now=True)),
                ('raw_stix', models.JSONField(blank=True, null=True)),
                ('source_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='dashboard.threatfeed')),
            ],
            options={
                'indexes': [models.Index(fields=['value'], name='dashboard_i_value_b59547_idx'), models.Index(fields=['type'], name='dashboard_i_type_560c82_idx'), models.Index(fields=['last_seen'], name='dashboard_i_last_se_87d52a_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'value'), name='unique_indicator')],
            },
        ),
    ]
