# Generated by Django 5.2.11 on 2026-03-02 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatfeed',
            name='last_count',
        ),
    ]
